name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.0
        with:
          java-version: "16"
          distribution: "adopt"
          cache: maven

      - name: Build Project
        run: mvn clean install

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/Numax-cz/napicuwebapi


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile

      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile